AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'test/fixtures/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'db/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'Guardfile'
    - 'config.ru'

Style/Encoding:
  Enabled: true